Style/Documentation:
  Enabled: false

LineLength:
   Max: 120

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "engines/*/db/**/*"
    - "engines/*/spec/test_app/**/*"

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/NumericPredicate:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

# Can remove when bbatsov/rubocop#4189 is released
Lint/AmbiguousBlockAssociation:
  Enabled: false
