FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Amble Api

## Auth  [/auth]

### Create New User [POST /auth]

This will createa new user in the system. The request will return a bunch of 
headers that you will need to include in all future request so that we can identify
the who the user i

+ Request (application/json)

        {
            "password": "123456",
            "password_confirmation": "123456",
            "email": "mylescc@gmail.com",
            "first_name": "Myles",
            "last_name": "Cowper-Coles"
        }

+ Response 200 (application/json)

    + Header

            access-token: dtpIRB3-Dxa3jlQHksUhMQ
            client: 23ag41TNIzrqzROOogrE9A
            expiry: 1525813931
            token-type: Bearer
            uid: mylescc@gmail.com

    + Body

            {
                "status": "success",
                "data": {
                    "id": 2,
                    "email": "mylescc@gmail.com",
                    "provider": "email",
                    "uid": "mylescc@gmail.com",
                    "first_name": "Myles",
                    "last_name": "Cowper-Coles",
                    "image": null,
                    "created_at": "2017-05-08T21:12:11.527Z",
                    "updated_at": "2017-05-08T21:12:11.608Z"
                }
            }

### Login User [POST /auth/sign_in]

You will just need to send the email and password to the server. Again it will return
a bunch of details about the user in the header which you'll need to use for future requests.Ro

+ Request (application/json)

        {
            "password": "123456",
            "email": "mylescc@gmail.com"
        }

+ Response 200 (application/json)

    + Header

            access-token: dtpIRB3-Dxa3jlQHksUhMQ
            client: 23ag41TNIzrqzROOogrE9A
            expiry: 1525813931
            token-type: Bearer
            uid: mylescc@gmail.com

    + Body

            {
                "data": {
                    "id": 2,
                    "email": "mylescc@gmail.com",
                    "provider": "email",
                    "uid": "mylescc@gmail.com",
                    "first_name": "Myles",
                    "last_name": "Cowper-Coles",
                    "image": null
                }
            }

## Steps [/register_steps]

### Register steps [POST]

So with this you just pass the date and the total number of steps for that day.
It will override any previous value they have for that day. This will also update
all walks that the current user is on with their progress. 

+ Request (application/json)

        {
            "date": "25-5-2017",
            "total_steps": 4343
        }

+ Response 200 (application/json)

# Routes Collection [/routes]

These are the routes that people will be able to find and sign up to.

## List All Routes [GET]

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 1,
                    "name": "M25 Walk",
                    "description": "A beautiful walk around the M25",
                    "distance_km": 120,
                    "distance_steps": 4334213
                }
            ],
            "count": 1
        }


#  Walks Collection [/walks]

## List All Walks [GET]

Lists all the walks for the current user.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 1,
                    "name": "M25 Walk",
                    "distance_total_km": 120,
                    "distance_complete_km": 3,
                    "distance_left_km": 117,
                    "steps_total": 12730,
                    "steps_complete": 1200,
                    "steps_left": 11530,
                    "started_at": "Some DateTime",
                    "completed_at": "Some DateTime",
                    "status": "in-progress"
                },
                {
                    "id": 1,
                    "name": "Walk to work",
                    "distance_total_km": 14,
                    "distance_complete_km": 10,
                    "distance_left_km": 4,
                    "steps_total": 4000,
                    "steps_complete": 1200,
                    "steps_left": 2800,
                    "started_at": "Some DateTime",
                    "completed_at": "Some DateTime",
                    "status": "complete"
                }
            ],
            "count": 2
        }



## Get a Walk [GET /walks/{id}]

Allows you get to just get a specific walk. I guess in the future this might contain
more details about how many steps they did on what days so people can make nice
graphs?

+ Response 200 (application/json)

        {
            "data": {
                "id": 1,
                "name": "M25 Walk",
                "distance_total_km": 120,
                "distance_complete_km": 3,
                "distance_left_km": 117,
                "steps_total": 12730,
                "steps_complete": 1200,
                "steps_left": 11530,
                "started_at": "Some DateTime",
                "completed_at": "Some DateTime",
                "status": "in-progress"
            }
        }
        
## Create a New Walk [POST]

If the user wants to start on a certain route, you just post the Id of the 
route that the user wants to start walking. 

+ Request (application/json)

        {
            "route_id": 1
        }

+ Response 201 (application/json)

        {
            "data": {
                "id": 1,
                "name": "M25 Walk",
                "distance_total_km": 120,
                "distance_complete_km": 3,
                "distance_left_km": 117,
                "steps_total": 12730,
                "steps_complete": 0,
                "steps_left": 12730,
                "started_at": "Now Date Time",
                "completed_at": null,
                "status": "in-progress"
            }